services:
  grafana:
    user: root
    container_name: 'maorwasihon-statadvanced-panel'

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
        grafana_version: ${GRAFANA_VERSION:-9.4.1}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
    volumes:
      - ../dist:/var/lib/grafana/plugins/maorwasihon-statadvanced-panel
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/maorwasihon-statadvanced-panel

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.maorwasihon-statadvanced-panel:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: maorwasihon-statadvanced-panel
      GRAFANA_IMAGE: grafana
      GRAFANA_VERSION: 9.4.1
